# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\vistaSolicitarPrestamo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(535, 498)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(0, 470, 711, 31))
        self.label_5.setStyleSheet("font: 87 18pt \"Arial Black\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.125, x2:0.334, y2:1, stop:0.0895522 rgba(146, 169, 190, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(350, 460, 231, 41))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(310, 170, 231, 211))
        self.label_7.setStyleSheet("image: url(:/images1/lufy.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(220, 20, 311, 61))
        self.label.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.leNombreLibro = QtWidgets.QLineEdit(Dialog)
        self.leNombreLibro.setGeometry(QtCore.QRect(60, 130, 231, 41))
        self.leNombreLibro.setObjectName("leNombreLibro")
        self.leNombreAutor = QtWidgets.QLineEdit(Dialog)
        self.leNombreAutor.setGeometry(QtCore.QRect(60, 200, 231, 41))
        self.leNombreAutor.setObjectName("leNombreAutor")
        self.btnSolicitar = QtWidgets.QPushButton(Dialog)
        self.btnSolicitar.setGeometry(QtCore.QRect(112, 280, 121, 41))
        self.btnSolicitar.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.btnSolicitar.setObjectName("btnSolicitar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Welcome to the team :D"))
        self.label.setText(_translate("Dialog", "Solicitar Prestamo"))
        self.leNombreLibro.setPlaceholderText(_translate("Dialog", "Ingresa el nombre del libro"))
        self.leNombreAutor.setPlaceholderText(_translate("Dialog", "Ingresa el nombre del autor"))
        self.btnSolicitar.setText(_translate("Dialog", "Solicitar Prestamo"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
