# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\agregarLibro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AgregarLibro(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(365, 458)
        
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 20, 221, 71))
        self.label.setStyleSheet("font: 75 16pt 'MS Shell Dlg 2';")
        self.label.setText("Agregar Libro")
        
        self.leNombre = QtWidgets.QLineEdit(Dialog)
        self.leNombre.setGeometry(QtCore.QRect(70, 130, 231, 31))
        self.leNombre.setPlaceholderText("Nombre del libro")
        
        self.leAutor = QtWidgets.QLineEdit(Dialog)
        self.leAutor.setGeometry(QtCore.QRect(70, 190, 231, 31))
        self.leAutor.setPlaceholderText("Autor del libro")
        
        self.leGenero = QtWidgets.QLineEdit(Dialog)
        self.leGenero.setGeometry(QtCore.QRect(70, 250, 231, 31))
        self.leGenero.setPlaceholderText("Género del libro")
        
        self.btnAgregar = QtWidgets.QPushButton(Dialog)
        self.btnAgregar.setGeometry(QtCore.QRect(140, 310, 93, 28))
        self.btnAgregar.setText("Agregar")
        
    
        QtCore.QMetaObject.connectSlotsByName(Dialog)

