# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Home_View.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HomeView(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(728, 585)

        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setGeometry(QtCore.QRect(0, 0, 971, 61))
        self.label_title.setStyleSheet("font: 87 18pt 'Arial Black'; background-color: lightblue;")
        self.label_title.setText("Biblioteca Virtual")

        self.btnAgregarLibro = QtWidgets.QPushButton(Dialog)
        self.btnAgregarLibro.setGeometry(QtCore.QRect(30, 80, 150, 41))
        self.btnAgregarLibro.setText("Agregar Libro")
        
        self.btnBuscarLibro = QtWidgets.QPushButton(Dialog)
        self.btnBuscarLibro.setGeometry(QtCore.QRect(200, 80, 150, 41))
        self.btnBuscarLibro.setText("Buscar Libro")
        
        self.btnRentarLibro = QtWidgets.QPushButton(Dialog)
        self.btnRentarLibro.setGeometry(QtCore.QRect(370, 80, 150, 41))
        self.btnRentarLibro.setText("Rentar Libro")

        QtCore.QMetaObject.connectSlotsByName(Dialog)