# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\vistaSolicitarPrestamo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BuscarLibro(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(535, 498)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(220, 20, 311, 61))
        self.label.setStyleSheet("font: 75 18pt 'MS Shell Dlg 2';")
        self.label.setText("Buscar Libro")
        
        self.leTitulo = QtWidgets.QLineEdit(Dialog)
        self.leTitulo.setGeometry(QtCore.QRect(60, 130, 231, 41))
        self.leTitulo.setPlaceholderText("Ingrese el título")
        
        self.leAutor = QtWidgets.QLineEdit(Dialog)
        self.leAutor.setGeometry(QtCore.QRect(60, 200, 231, 41))
        self.leAutor.setPlaceholderText("Ingrese el autor")
        
        self.leGenero = QtWidgets.QLineEdit(Dialog)
        self.leGenero.setGeometry(QtCore.QRect(60, 270, 231, 41))
        self.leGenero.setPlaceholderText("Ingrese el género")
        
        self.btnBuscar = QtWidgets.QPushButton(Dialog)
        self.btnBuscar.setGeometry(QtCore.QRect(112, 340, 121, 41))
        self.btnBuscar.setText("Buscar Libro")
        
        self.lblResultado = QtWidgets.QLabel(Dialog)
        self.lblResultado.setGeometry(QtCore.QRect(60, 400, 400, 41))
        self.lblResultado.setStyleSheet("font: 75 12pt 'MS Shell Dlg 2';")
        
        QtCore.QMetaObject.connectSlotsByName(Dialog)
